service: lambda-openai-slack-bot
provider:
  name: aws
  region: us-east-1
  runtime: python3.9
  # stage: prod
  timeout: 120
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:us-east-1:*:table/openai-slack-bot-context"

functions:
  mention:
    handler: handler.lambda_handler
    events:
      - http:
          method: post
          path: /slack/events

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: openai-slack-bot-context # ${self:provider.environment.DYNAMODB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: expire_at
          Enabled: true

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
