# org: nalbam
app: lambda-slack-ai-bot
service: lambda-slack-ai-bot
provider:
  name: aws
  region: us-east-1
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  memorySize: 5120
  timeout: 300
  environment:
    BASE_NAME: slack-ai-bot
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:*:*:table/${self:provider.environment.BASE_NAME}-*"

functions:
  mention:
    handler: handler.lambda_handler
    events:
      - http:
          method: post
          path: /slack/events
    tags:
      Project: ${self:provider.environment.BASE_NAME}

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.BASE_NAME}-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          AttributeName: expire_at
          Enabled: true
        Tags:
          - Key: Project
            Value: ${self:provider.environment.BASE_NAME}

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
