service: lambda-openai-slack-bot
provider:
  name: aws
  region: us-east-1
  runtime: python3.9
  # stage: prod
  timeout: 120
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:us-east-1:968005369378:table/openai-slack-bot-history"

functions:
  openai:
    handler: handler.lambda_handler
    events:
      - http:
          method: post
          path: /slack/events

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: openai-slack-bot-history # ${self:provider.environment.DYNAMODB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: thread_ts
            AttributeType: S
        KeySchema:
          - AttributeName: thread_ts
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
